name: Release

on:
  push:
    tags:
      - 'v*'  # Sadece v1.2.1 gibi tagler için çalıştır

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Set Go Modules
        run: |
          export GO111MODULE=on
          go mod tidy
          go mod vendor

      - name: Build Binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o docm-linux-amd64 main.go
          GOOS=darwin GOARCH=amd64 go build -o docm-mac-amd64 main.go
          GOOS=windows GOARCH=amd64 go build -o docm-windows-amd64.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            docm-linux-amd64
            docm-mac-amd64
            docm-windows-amd64.exe
